apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
<<<<<<< HEAD
          image: nginxinc/nginx-unprivileged
=======
          image: nginxinc/nginx-unprivileged:stable
>>>>>>> d3eafd0aab8d1502d15552170abd13d1ba11deea
          ports:
            - containerPort: 80
 # Add Security Context to the Pod           
          securityContext:
            runAsNonRoot: true # Ensures the container runs as a non-root user
            allowPrivilegeEscalation: false  # Prevents the container from gaining additional privileges
